### ISSUE TITLE
List of algorithms is incomplete

### ISSUE THREAD

**Issue by aryadas98** [NJACKWinterOfCode/algorithms_with_git#13]
The list of algorithms in the project [README](https://github.com/NJACKWinterOfCode/algorithms_with_git/blob/master/README.md) is incomplete. In particular, the following algorithms are missing:
* [Caesar's Cipher](https://github.com/NJACKWinterOfCode/algorithms_with_git/tree/master/algorithms/Caesar's_cipher)
* [array_rotation_by_1](https://github.com/NJACKWinterOfCode/algorithms_with_git/tree/master/algorithms/array_rotation_by_1)

**Comment by gsoc18** [comment]
The Pull Request was already made for this issue earlier. Kindly review it.
