### ISSUE TITLE
Add Rabin-Karp and Naive String matching

### ISSUE THREAD

**Issue by CoderJolly** [NJACKWinterOfCode/algorithms_with_git#137]

**Comment by saurabhshadow** [comment]
I can do this.
Assign this work to me.

**Comment by CoderJolly** [comment]
Actually, I am not the admin at NWoC. I am a participant as well.
We had to open a legitimate issue in any of the projects announced for NWoC which I have done.
So, I am nt sure who is merging the PR and who is monitering

**Comment by saurabhshadow** [comment]
Okay

**Comment by saurabhshadow** [comment]
Close this issue!
